/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Use global types since we're using CDN scripts in index.html to ensure reliability
declare global {
  interface Window {
    jspdf: any;
    html2canvas: any;
  }
}

export async function generatePDF(_unused_element: HTMLElement, filename: string) {
  try {
    // Select the invoice preview directly by ID as requested
    const invoiceElement = document.getElementById("invoice-preview");
    
    if (!invoiceElement) {
      throw new Error("Element with ID 'invoice-preview' not found in the DOM.");
    }

    // Capture with a brief delay to ensure styles are applied
    await new Promise(resolve => setTimeout(resolve, 300));

    // Access jsPDF from the global window object (loaded via CDN for reliability)
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({
      orientation: 'p',
      unit: 'mm',
      format: 'a4'
    });

    // Use the doc.html() method to render the HTML element into the PDF
    // This is the most reliable way as it handles styling and resolution better
    await doc.html(invoiceElement, {
      callback: function (doc: any) {
        // Add professional footer text as requested
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by NudgePay (nudgepayments.com)", 105, 290, { align: 'center' });
        
        // Finalize and save the document
        doc.save(filename || "invoice.pdf");
      },
      x: 0,
      y: 0,
      width: 210, // A4 width in mm
      windowWidth: 794, // Standard A4 pixel width at 96dpi
      autoPaging: 'text',
      html2canvas: window.html2canvas
    });

    return true;
  } catch (error) {
    // We log only the message to avoid circular structure errors in console logs
    const message = error instanceof Error ? error.message : "PDF Generation failed";
    console.error('PDF Error:', message);
    throw new Error(message);
  }
}
